export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAIL = 'GET_TRANSACTIONS_FAIL';

export const GET_TRANSACTION_TYPES_REQUEST = 'GET_TRANSACTION_TYPES_REQUEST';
export const GET_TRANSACTION_TYPES_SUCCESS = 'GET_TRANSACTION_TYPES_SUCCESS';
export const GET_TRANSACTION_TYPES_FAIL = 'GET_TRANSACTION_TYPES_FAIL';

export const ADD_TRANSACTION_REQUEST = 'ADD_TRANSACTION';
export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS';
export const ADD_TRANSACTION_FAIL = 'ADD_TRANSACTION_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const GET_TOTALS_REQUEST = 'GET_TOTALS_REQUEST';
export const GET_TOTALS_SUCCESS = 'GET_TOTALS_SUCCESS';
export const GET_TOTALS_FAIL = 'GET_TOTALS_FAIL';


